---
# tasks file for roles/bkp_projects
    - name: Create project backup directory
      file:
        path: "{{ item.dir }}"
        state: directory
        mode: 0700
      loop: "{{ dirs }}"
    - name: Create project object backups
      shell: >
        oc login -u system:admin > /dev/null &&
        for PROJECT in $(oc get projects | awk '{ print $1 }' | grep -v NAME);
        do
          mkdir "{{ item.dir }}"/${PROJECT} &&
          oc project $PROJECT &&
          oc get -o yaml --export all > "{{ item.dir }}"/${PROJECT}/${PROJECT}.yaml &&
          for OBJECT in rolebindings serviceaccounts secrets imagestreamtags cm \
          egressnetworkpolicies rolebindingrestrictions limitranges resourcequotas \
          pvc templates cronjobs statefulsets hpa deployments replicasets \
          poddisruptionbudget endpoints deploymentconfig;
          do
            oc get -o yaml --export $OBJECT > "{{ item.dir }}"/${PROJECT}/$OBJECT.yaml;
          done; 
        done 
      loop: "{{ dirs }}"
    - name: Compress project directory
      archive:
        path: "{{ item.dir }}"
        dest: "{{ item.bkpfile }}"
      loop: "{{ dirs }}"
    - name: Download backups
      fetch:
        src: "{{ item.bkpfile }}"
        dest: "{{ destbackup }}"
      loop: "{{ dirs }}"
    - name: Remove backup on master servers
      file:
        path: "{{ item.bkpfile }}"
        state: absent
      loop: "{{ dirs }}"
    - name: Remove project backup directory
      file:
        path: "{{ item.dir }}"
        state: absent
      loop: "{{ dirs }}"
